repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.4.2
      hooks:
          # Run the linter
          - id: ruff
            types: [python]
          # Run the formatter
          - id: ruff-format
            types: [python]

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.10.0
      hooks:
          - id: mypy
            types: [python]
            args: [--strict, --ignore-missing-imports]